"""api_calls 增加 gateway_request_id

Revision ID: b64490270183
Revises: c8f4a1d9e6b2
Create Date: 2026-08-28 10:02:03.560294

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b64490270183"
down_revision: str | Sequence[str] | None = "c8f4a1d9e6b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_calls", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gateway_request_id", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_api_calls_gateway_request_id"), ["gateway_request_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_calls_gateway_request_id"))
        batch_op.drop_column("gateway_request_id")

    # ### end Alembic commands ###
